#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `shell/functions/_c`. Typically:
#
#   c my-project

cd "$PROJECTS/$1"
